### ISSUE TITLE
Question about CheckpointStores in the sample application

### ISSUE THREAD

**Issue by LockTar** [Eventuous/dotnet-sample#4]
Hi,

I have a question about checkpoint stores in the sample application. See [Registrations.cs#L42-L59](https://github.com/Eventuous/dotnet-sample/blob/main/Bookings/Registrations.cs#L42-L59).

If saw the following documentation about [available stores](https://eventuous.dev/docs/subscriptions/checkpoint/#available-stores).

If I understand correctly there is now a general checkpoint store with this line `services.AddCheckpointStore<MongoCheckpointStore>();`.
And a specific checkpoint store `.UseCheckpointStore<MongoCheckpointStore>()` for `BookingsProjections`.

Is the general store in this sample application then not used anymore?

**Comment by alexeyzimarev** [comment]
It is probably used in the integration subscription.
