### ISSUE TITLE
await EnsureRoomAvailable(roomId, period, isRoomAvailable);

### ISSUE THREAD

**Issue by jenssc** [Eventuous/dotnet-sample#5]
Hi
Isn't it a bug that nothing is using anything from the call to EnsureRoomAvailable ?
The code will never wait for anything to get completed and there by you end up creating the event before ensuring that the room is available.

**Comment by alexeyzimarev** [comment]
It's definitely used
https://github.com/Eventuous/dotnet-sample/blob/5f5cdb03e55012e0eefa2a2df0d43f79b1384608/Bookings.Domain/Bookings/Booking.cs#L7-L18

**Comment by jenssc** [comment]
Ahhh... sorry :-)

**Comment by LockTar** [comment]
@jenssc can this be closed?

**Comment by jenssc** [comment]
Sure... my bad :-)
